# Generated by Django 2.2.12 on 2021-12-19 04:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True, unique=True)),
                ('design', models.CharField(blank=True, choices=[('', 'Select'), ('narrow fitting', 'narrow fitting'), ('Slim Fit', 'Slim Fit')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=700, null=True)),
                ('delivery', models.CharField(blank=True, choices=[('', 'Select'), ('Normal', 'Normal'), ('Urgent', 'Urgent')], max_length=100, null=True)),
                ('price', models.PositiveIntegerField()),
                ('payment', models.PositiveIntegerField(blank=True)),
                ('received_date', models.DateTimeField()),
                ('due', models.PositiveIntegerField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
    ]
